All:
	python run_experiment.py mnist10 nl

mnist10_nl:
	python run_experiment.py mnist10 nl

mnist10_al:
	python run_experiment.py mnist10 al

cifar10_nl:
	python run_experiment.py cifar10 nl

cifar10_al:
	python run_experiment.py cifar10 al

clean:
	rm *_log.txt
